shell = "zsh"

[plugins]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"

[plugins.zsh-you-should-use]
github = "MichaelAquilina/zsh-you-should-use"

[plugins.zsh-autopair]
github = "hlissner/zsh-autopair"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

