[tools]
node = "22.13.0"

# npmパッケージ
"npm:@antfu/ni" = "latest"
"npm:@openai/codex" = "latest"
"npm:@devcontainers/cli" = "latest"

# 言語サーバー（LSP）
"aqua:LuaLS/lua-language-server" = "latest"
"npm:typescript-language-server" = "latest"
"npm:@astrojs/language-server" = "latest"

